// Auto-generated types for Supabase
// This file is generated by supabase CLI, but we define it manually here

export interface Database {
  public: {
    Tables: {
      portfolios: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          base_currency: string;
          created_at: string;
        };
        Insert: {
          name: string;
          description?: string | null;
          base_currency?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          base_currency?: string;
        };
      };
      assets: {
        Row: {
          id: string;
          name: string;
          ticker: string | null;
          type: 'stock' | 'etf' | 'crypto' | 'cash';
          currency: string;
          exchange: string | null;
          created_at: string;
        };
        Insert: {
          name: string;
          ticker?: string | null;
          type: 'stock' | 'etf' | 'crypto' | 'cash';
          currency: string;
          exchange?: string | null;
        };
        Update: {
          name?: string;
          ticker?: string | null;
          type?: 'stock' | 'etf' | 'crypto' | 'cash';
          currency?: string;
          exchange?: string | null;
        };
      };
      transactions: {
        Row: {
          id: string;
          portfolio_id: string;
          asset_id: string;
          type: 'buy' | 'sell' | 'dividend' | 'fee';
          quantity: number;
          unit_price: number;
          fee: number;
          date: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          portfolio_id: string;
          asset_id: string;
          type: 'buy' | 'sell' | 'dividend' | 'fee';
          quantity: number;
          unit_price: number;
          fee?: number;
          date: string;
          notes?: string | null;
        };
        Update: {
          type?: 'buy' | 'sell' | 'dividend' | 'fee';
          quantity?: number;
          unit_price?: number;
          fee?: number;
          date?: string;
          notes?: string | null;
        };
      };
    };
  };
}
